# Infrastructure Configs
spark.hadoop.fs.s3a.endpoint=http://minio:9000
spark.hadoop.fs.s3a.access.key=admin
spark.hadoop.fs.s3a.secret.key=password
spark.hadoop.fs.s3a.path.style.access=true
spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.connection.ssl.enabled=false

# Application Logic Configs
spark.app.input_path=s3a://sampra/input/
spark.app.output_path=s3a://sampra/output/first/test_data.csv
spark.app.file_format=csv
spark.app.batch_id=2024_01_01


# pipeline 2
spark.app.input_path=s3a://sampra/input/ratings.dat
spark.app.output_path=s3a://sampra/output/first/test_data.csv
spark.app.file_format=csv
spark.app.batch_id=2024_01_01


#pipeline 3
spark.app.input_path_1=s3a://sampra/input/u.data 
spark.app.input_path_2=s3a://sampra/input/u.item 


#pipeline 5
spark.app.input_path_3 = s3a://sampra/input/yelp_academic_dataset_business.json
spark.app.input_path_4 = s3a://sampra/input/yelp_academic_dataset_checkin.json
spark.app.input_path_5 = s3a://sampra/input/yelp_academic_dataset_review.json
spark.app.input_path_6 = s3a://sampra/input/yelp_academic_dataset_tip.json
spark.app.input_path_7 = s3a://sampra/input/yelp_academic_dataset_user.json



